[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "scikit-learn",
    "abc",
    "pandas",
    "numpy",
    "matplotlib",
    "scipy",
    "lmfit",
    "multiprocessing",
    "functools",
    "joblib",
    "tqdm",
    "os",
    "struct",
    "time",
    "warnings",
    "time",
    "math"
]

build-backend = "setuptools.build_meta"

[project]
version = "0.1.5"
name="piicrgmms"
authors = [
{name = "Colin Weber", email = "colin.weber.27@gmail.com"},
{name = "Dwaipayan Ray"},
{name = "Adrian Valverde", email = "adrian.antonio.valverde@gmail.com"}
]
maintainers = [{name = "Adrian Valverde", email = "adrian.antonio.valverde@gmail.com"}]
description = "A data analysis package for PI-ICR Mass Spectrometry"
readme="README.md"
license = {file = "LICENSE.txt"}
keywords=["Gaussian Mixture Models","Clustering Algorithms","Machine Learning","Mass Spectrometry"]
classifiers=[
"Development Status :: 4 - Beta",
"Programming Language :: Python :: 3",
"License :: OSI Approved :: MIT License",
"Intended Audience :: Science/Research",
"Natural Language :: English",
"Operating System :: Microsoft :: Windows",
"Topic :: Scientific/Engineering",
"Topic :: Scientific/Engineering :: Artificial Intelligence",
"Topic :: Scientific/Engineering :: Physics",
]
[project.urls]
Homepage = "https://pypi.org/project/piicrgmms/"
Repository = "https://github.com/AAValverde/piicrgmms"
Download = "https://pypi.org/project/piicrgmms/#files"
